### ISSUE TITLE
parametrized test

### ISSUE THREAD

**Issue by iulusoy** [pauleonix/ssd_course#7]
@pauleonix could you push your test as it is to the repo, then I can make suggestions.

**Comment by pauleonix** [comment]
See #8 for my tests. I decided to do not use fixtures at all and instead use normal functions. For my purpose this should be fine?

**Comment by pauleonix** [comment]
It was merged into main.

**Comment by pauleonix** [comment]
@iulusoy any ideas about the other issues (#10, #11 and #12)?

**Comment by iulusoy** [comment]
The tests looked fine to me, quite readable and is good like this.

**Comment by iulusoy** [comment]
I will take a look at the other issues, early next week.

**Comment by pauleonix** [comment]
@iulusoy I figured most things out. The only thing left seems to be why `pip` doesn't install dependencies automatically (#12).
